version: '2'
services: 
  mysql:
    image: registry.saas.hand-china.com/tools/mysql
    build: /docker/mysql
    volumes:
      - ./mysql/db:/var/lib/mysql
    enviroment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456

  java:
    image: registry.saas.hand-china.com/hap-cloud/base
    build: /docker/java
    volumes:
      - ./java:/opt/Exam1
    ports:
      - 8080
      - 3306:3306
    links:
      - mysql:default
    command: java -jar Exam1.jar 1